### ISSUE TITLE
Container takes 10s timeout to stop, exits with code 137

### ISSUE THREAD

**Issue by rulatir** [oanhnn/docker-laravel-echo-server#3] opened 2019-03-29 06:56 UTC
Looks like it isn't handling SIGTERM properly and relies on docker eventually SIGKILLing it?

**Comment by oanhnn** [comment] 2019-04-01 02:57
Thank you! I need confirm this problem. Can you describe how to reproduce it?

**Comment by oanhnn** [comment] 2020-04-12 18:35
I close this issue because i can't reproduce it.
Everyone has same problem can re-open it.

**Closed as completed by oanhnn** 2020-04-12 18:35 UTC
Labels: bug, question
